### ISSUE TITLE
Show node group name in nodes table

### ISSUE THREAD

**Issue by michaeljguarino** [pluralsh/console#29]
## Use Case
It's sometimes helpful to see what nodegroup a node belongs to get a feel for what portion of the topology it serves.

## Ideas of Implementation
Just write a sequence of getters in the node labels to find it for each cloud

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by DavidSpek** [comment]
All our node groups have a label with the node group name, so that can be used for this. However, this label is not split across the AZs so if you also want information about what AZ the node is in the Kubernetes label should be used for that.
