### ISSUE TITLE
Plural Init in existing git repo has unintended side effects

### ISSUE THREAD

**Issue by ycryptx** [pluralsh/console#37]
## Summary
Doing a `plural init` in an existing repo does the following undesired things:
Overwrites `.gitignore` file

## Reproduction
Run `plural init` in an existing project

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by michaeljguarino** [comment]
I do know we overwrite .gitignore, I can't imagine we update .DS_STORE though, is that possibly due to vscode?

**Comment by michaeljguarino** [comment]
We should probably make our .gitignore match closer to gh defaults though, including ignoring ds store

**Comment by michaeljguarino** [comment]
this should address .DS_STORE files and other vscode artifacts not covered in our default gitignore: https://github.com/pluralsh/plural-cli/pull/25
